BASE=~/source/freeswitch-1.2.23/

LOCAL_OBJS=\
		  acd_agent.o acd_tiers.o acd_queue.o acd_tools.o acd_state.o acd_config.o
LOCAL_SOURCES=\
		  acd_agent.cpp acd_tiers.cpp acd_queue.cpp acd_tools.cpp acd_state.cpp acd_config.cpp


include $(BASE)/build/modmake.rules

LOCAL_CFLAGS=-I./include/
